# Generated by Django 4.2.4 on 2023-08-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0008_ansquestion'),
        ('make_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_article', to='content_management.teacherarticle'),
        ),
    ]
