# Generated by Django 4.2.4 on 2023-08-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_teacherarticle_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherarticle',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='articleImg'),
        ),
    ]
