# Generated by Django 4.2.4 on 2023-08-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_alter_teacherarticle_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=500),
        ),
    ]
