# Generated by Django 4.2.4 on 2023-08-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0006_askquestion_question_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askquestion',
            name='question_ans',
        ),
    ]
